defaults: &defaults
  max_unread_count: 200
  default_favicon: <%= "#{Rails.root}/public/img/icon/default.png" %>
  subscribe_limit: 5000
  save_pin_limit: 100
  crawl_interval: 30
  allow_tags: <%= %w(a i u b em strong table tr td th tbody font center div pre code blockquote ins del img br p hr ul li ol dl dt dd) %>
  allow_attributes: <%= %w(src width height border alt title href color size align) %>
  publish_interval: <%= 3 * 60 * 60 %>
  black_list_words: <%= %w(続きを読む amp nbp SocialGameInfo https http isapostfrom シリーズ オリジナル twitter 公式twitter ストーリー プレスリリース 東京都内 イベント キャンペーン 主人公 期間限定 オリジナル 公式サイト アンケート 製作委員会 世界 アップデート 情報 ラインナップ com タイトル プレイ スペシャル 劇場版) %>
  media:
    url: http://fujossy.dev
    article_create_path: /articles/create_all.json

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  media:
    url: https://fujossy.jp
    article_create_path: /articles/create_all.json
